from typing import Annotated, Literal, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class State(TypedDict):
    # ==================================================
    # 1. MESSAGES
    # ==================================================

    # Message history from the user, LLM, system, and tool.
    messages: Annotated[
        list[BaseMessage],
        add_messages,
    ]

    # ==================================================
    # 2. DATASET
    # ==================================================

    # Path to the dataset.
    dataset_path: str | None

    # Dataset inspection result from Python.
    summary: dict | None

    # Dataset analysis result from the LLM.
    summary_llm: str | None

    # ==================================================
    # 3. PROBLEM PROPOSAL AND HUMAN REVIEW
    # ==================================================

    # Problem proposal from the LLM.
    problem_proposal: dict | None

    # Target confirmed by the user.
    target_column: str | None

    # Confirmed problem type.
    problem_type: (Literal["regression", "classification"]| None)

    # User approval status.
    approval_status: (Literal["pending", "approved", "rejected"]| None)

    # Additional user feedback.
    user_feedback: str | None

    # Detailed target analysis.
    target_analysis: dict | None

    # ==================================================
    # 4. NOTEBOOK PLAN
    # ==================================================

    # Notebook plan.
    notebook_plan: dict | None

    # Plan validation status.
    plan_validation_status: (Literal["pending", "valid", "invalid"]| None)

    # Plan errors.
    plan_validation_errors: list[dict] | None

    # Number of plan repair attempts.
    fix_plan_attempts: int

    # ==================================================
    # 5. CELL GENERATION
    # ==================================================

    # List of cells generated by the LLM.
    notebook_cells: list[dict] | None

    # Cell generation status.
    section_generation_status: (Literal["pending", "success", "failed"]| None)

    # Errors raised while generating each section/cell.
    section_generation_errors: list[dict] | None

    # Index of the next section to generate.
    current_section_index: int

    # IDs of successfully generated sections.
    generated_section_ids: list[str]

    # Number of API retries for the current section.
    section_retry_attempts: int

    # ==================================================
    # 6. CELL VALIDATION AND REPAIR
    # ==================================================

    # Cell validation status.
    validation_cell_status: (
        Literal["pending", "valid", "invalid"]
        | None
    )

    # Cell errors.
    validation_cell_errors: list[dict] | None

    # Number of cell repair attempts.
    fix_cell_attempts: int

    # IDs of successfully repaired cells.
    fixed_cell_ids: list[str] | None

    # Cells that could not be repaired.
    fix_cell_failures: list[dict] | None

    # ==================================================
    # 7. PIPELINE REVIEW
    # ==================================================

    # LLM semantic review status for the entire pipeline.
    pipeline_review_status: (
        Literal["pending", "valid", "invalid", "failed"]
        | None
    )

    # Semantic errors found by the pipeline reviewer.
    pipeline_review_errors: list[dict] | None

    # Number of repair attempts for semantic pipeline errors.
    pipeline_fix_attempts: int

    # ==================================================
    # 8. NOTEBOOK BUILD
    # ==================================================

    # Output notebook file path.
    notebook_path: str | None

    # Notebook file creation status.
    build_status: (
        Literal["pending", "success", "failed"]
        | None
    )

    # Error occurring during notebook file creation.
    build_error: str | None
    # ==================================================
    # 9. NOTEBOOK EXECUTION
    # ==================================================

    # Notebook execution status.
    execution_status: (
        Literal[
            "pending",
            "success",
            "failed",
        ]
        | None
    )

    # Error information when notebook execution fails.
    execution_error: dict | None

    execution_attempts: int

    execution_fix_attempts: int

    # ==================================================
    # 10. GLOBAL ERROR
    # ==================================================

    # Most recent general workflow error.
    error: str | None


def create_initial_state( dataset_path: str, ) -> State:
    return {
        # 1. Messages
        "messages": [],

        # 2. Dataset
        "dataset_path": dataset_path,
        "summary": None,
        "summary_llm": None,

        # 3. Problem proposal + HITL
        "problem_proposal": None,
        "target_column": None,
        "problem_type": None,
        "approval_status": None,
        "user_feedback": None,
        "target_analysis": None,

        # 4. Notebook plan
        "notebook_plan": None,
        "plan_validation_status": None,
        "plan_validation_errors": None,
        "fix_plan_attempts": 0,

        # 5. Section generation
        "notebook_cells": None,
        "section_generation_status": None,
        "section_generation_errors": None,
        "current_section_index": 0,
        "generated_section_ids": [],
        "section_retry_attempts": 0,

        # 6. Cell validation
        "validation_cell_status": None,
        "validation_cell_errors": None,
        "fix_cell_attempts": 0,
        "fixed_cell_ids": None,
        "fix_cell_failures": None,

        # 7. Pipeline review
        "pipeline_review_status": None,
        "pipeline_review_errors": None,
        "pipeline_fix_attempts": 0,

        # 8. Notebook build
        "notebook_path": None,
        "build_status": None,
        "build_error": None,

        # 9. Execution
        "execution_status": None,
        "execution_error": None,
        "execution_attempts": 0,
        "execution_fix_attempts": 0,

        # 10. Global error
        "error": None,
    }
